### ISSUE TITLE
babel-loader conflict

### ISSUE THREAD

**Issue by soulfresh** [morewings/cra-template-npm-library#313]
I just tried generating a new project with this template and I'm getting a babel-loader conflict error from create react app. It looks like Docz is importing a newer version of babel-loader than create react app app will allow. I quickly tried downgrading docz to 2.0.0 but that did not help.

Everything seems to work with `SKIP_PREFLIGHT_CHECK=true` but I'm not sure what other issues that may introduce.

__CRA Error__
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/marc/Development/atom-dance/react-popover/react-popover/node_modules/babel-loader (version: 8.2.2)
```

__NPM LS__
```
├─┬ docz@2.3.1
│ └─┬ gatsby@2.29.2
│   └── babel-loader@8.2.2
└─┬ react-scripts@4.0.1
  └── babel-loader@8.1.0
```

**Comment by morewings** [comment]
Thanks for reporting. The warning was triggered because Docz uses separate babel config then CRA. Using ‘SKIP_PREFLIGHT_CHECK=true’ should be safe. 
I will provide update soon.
