### ISSUE TITLE
Great template, is there an example of using with typescript?

### ISSUE THREAD

**Issue by chriszrc** [morewings/cra-template-npm-library#760]
Need typescript :'(

**Comment by morewings** [comment]
For now, I can help you just with good advice ;):
1. Run `yarn create react-app my-app --template typescript`
2. Copy this template over your installation
3. Add `@rollup/plugin-typescript` to config
4. Merge `package.json` commands
5. PROFIT

**Comment by chriszrc** [comment]
@morewings yeah, I ended up going with tsdx - https://tsdx.io/
